export default {
  filter_id: 0,
  active_item_type: 'offers',
  visablity: undefined,
  item_edited: {},
  promoted_items: [],
  last_items: [],
  item_current: {
    "id":0,
    "title":"Product title",
    "img":"/assets/product-m-46bd2271a0899550e3039b1c47376a8571ac37304fb4803d3f7754989584243f.png",
    "price":"Members only USD/MT",
    "delivery":"EXW USA",
    "tooltip":"Applicable incoterms:\u003cbr\u003eEXW",
    "type":"offer",
    "can_bid":true,
    "verified":false,
    "hot":true,
    "r_id":1,
    "company":{
      "id":1,
      "logo":"/files/representations/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBIdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b3b276bc87ae883fd1817acada48a40a02c64663/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCam9MY21WemFYcGxTU0lNTVRFd2VERXhNQVk2QmtWVSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--af9fde47c2762b7395d230054fada775eae756c6/b_logo.png",
      "title":"GLobalSupplies",
      "rating_code":"platinum",
      "on_map":true,
      "processes_count":0,
      "offers_count":5,
      "requests_count":7,
      "role":"trader",
      "category_ids":[2,3,1],
      "r_id":1,
       "info":[{"title":"Role","value":"Trader"}],
       "certificates":[],
    },
    "bid":{},
    "info":[{"title":"Info","data":[{"title":"Countries of origin","value":"USA"},{"title":"Port","value":"Abu Dhabi"}]},{"title":"Shipping \u0026 Payment details","data":[{"title":"Paymenterms","value":"LC,30% Prepayment"},{"title":"Incoterms","value":"EXW"}]},{"title":"Packing","data":[{"title":"Package type","value":"Carton 10 kg"}]}],
    "bids":[],
    "recomendations":[],
    "certificates":[],
    "description":"30% prepayment/70% afterpayment"
  },
  active_item:{
    bids: []
  },
  full_item:{
    bids: [],
    images:[],
  },
  item_deleted: false,
  item_saved: false,
  items: [],
  my_items: [],
  total: 0,
  filters: {
    price: [0, 100000],
    permissions: [],
    payment_types: [],
    delivery: [],
    origins: [],
    title:"",
  },
  sorting: {
      direction: "DESC",
      field: "updated_at"
  },
  page: 1,
  selected_items: {},
}
