development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://#{Rails.application.secrets[:redis][:host]}:#{Rails.application.secrets[:redis][:port]}/1" } %>
  channel_prefix: global_supplies_development
test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://#{Rails.application.secrets[:redis][:host]}:#{Rails.application.secrets[:redis][:port]}/1" } %>
  channel_prefix: global_supplies_production
