default: &default
  host: <%= Rails.application.secrets[:database][:host] %>
  # port: <%= Rails.application.secrets[:database][:port] %>
  adapter: postgresql
  encoding: unicode
  database: <%= Rails.application.secrets[:database][:name] %>
  pool: <%= Rails.application.secrets[:database][:pool] %>
  reaping_frequency: <%= Rails.application.secrets[:database][:reaping_frequency] %>
  username: <%= Rails.application.secrets[:database][:username] %>
  password: <%= Rails.application.secrets[:database][:password] %>

test: *default
testing: *default
staging: *default
development: *default
production: *default
bamboo: *default
